"""Create Tables

Revision ID: f78dee95ba59
Revises: 
Create Date: 2025-06-07 18:18:40.844430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78dee95ba59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=12, scale=9), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=12, scale=9), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_data',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temp_min', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('temp_max', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('temp_mean', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('precip_sum', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rain_sum', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('snow_sum', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sunsh_time', sa.Integer(), nullable=False),
    sa.Column('wind_dir', sa.Integer(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data')
    op.drop_table('location')
    # ### end Alembic commands ###
